jenkins:
  systemMessage: "Configuration as Code"
unclassified:
  shell:
    shell: "bash"
  globalLibraries:
    libraries:
      - defaultVersion: "master"
        name: "satqe_pipeline_lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/mkrzyzanowski/blog-001.git"
                traits:
                - "gitBranchDiscovery"
               
jenkins:
  systemMessage: "Configuration as Code"                
jobs:
   multibranchPipelineJob('configuration-as-code-via-url') {
  branchSources {
      git {
          id = 'configuration-as-code'
          remote('https://github.com/Mahm0udSaed/simple-java-maven-app.git')
      }
  }
  

 

}
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.3" 

